[build]
  command = "npm run build"
  publish = "dist/minviv-dashboard/browser"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "9"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
